### ISSUE TITLE
Add support for async actions

### ISSUE THREAD

**Issue by dpinart** [steelsojka/aurelia-redux-plugin#3]
Hi,
First of all, congratulations for the good work

It would be interesting to support async actions. Currently, using one of the existing middlewares like redox-thunk or redux-promise overrides the dispatch wrapper and avoids the select decorator to get notified when async actions update the state.

I think it would be really easy to implement this feature by just checking at Store.dispatch method if action is a promise, a function or a standard action.

**Comment by steelsojka** [comment]
Done! Thanks for the contribution. I'll get unit tests written soon... If there are any problems let me know!
